### ISSUE TITLE
Build Voice Interaction more generic and strong

### ISSUE THREAD

**Issue by maze-runnar** [SARTHAK1SINGH/HackthonFB#17]
As we have only 20 days left and a lot of things still to do like deployment, production build, the presentation so I want you to focus on the project's voice interaction part. Make it more elegant.

references : 

1 - https://youtu.be/HXLmhyWkvFM
2 - https://wit.ai/docs/http/20200513#post__speech_link

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH @saurabh28march take a look at video and get more idea about how voice interaction works.Then we will proceed to another idea to work.

**Comment by SARTHAK1SINGH** [comment]
isko use krke download pdf , show graphs, show statistics kr skte hai kya ?

**Comment by maze-runnar** [comment]
ok
