### ISSUE TITLE
Add requirements.txt to project

### ISSUE THREAD

**Issue by maze-runnar** [SARTHAK1SINGH/HackthonFB#6]
While updating the repo and introducing a new third-party package, please add those dependencies to requirements.txt to ease of setup

**Comment by SARTHAK1SINGH** [comment]
okk go for it you can work on it 
![bd547e20059ae3a027650fdb2bddf6be](https://user-images.githubusercontent.com/44469087/89727129-b86a7200-da3f-11ea-8004-fff81fa953f4.gif)
